runtime: python311

env: standard

entrypoint: python app/run_main.py

env_variables:
  GEMINI_API_KEY: ${GEMINI_API_KEY}
  GEMINI_MODEL: "gemini-3.5-flash-lite"
  PARALLEL_API_KEY: ${PARALLEL_API_KEY}
  MAX_REFINEMENTS: "0"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"

manual_scaling:
  instances: 1

instance_class: F1
