services:
  - type: web
    name: cineflow
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.web_app:app
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyBVuglJuhtq44M3GSetWl0WunGZTT7a_DE
      - key: GEMINI_MODEL
        value: gemini-3.5-flash-lite
      - key: PARALLEL_API_KEY
        value: ijWTrF4yby5cR8Gs4y0HpbEjXqlKyN6PBJC_Qun0
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8000"

